elastic17:
 image: mibusuio/elasticsearch1.7
 ports:
  - "9200:9200"
  - "9300:9300"
 volumes:
  - ./config:/usr/share/elasticsearch/config
  - ./esdata:/usr/share/elasticsearch/data
kibana4.7:
 image: mibusuio/kibana4.1
 ports:
  - "5601:5601"
 links:
  - elastic17:elasticsearch
